version: '3.8'

services:
  backend:
    build: ./job-diva-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=30042002
      - DB_NAME=jobportal
    depends_on:
      - db
    volumes:
      - ./job-diva-backend:/app
      - /app/node_modules

  frontend:
    build: ./job-diva-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./job-diva-frontend:/app
      - /app/node_modules

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jobportal
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
